// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddScore(arg1, arg2, arg3) {
  return window['go']['app']['App']['AddScore'](arg1, arg2, arg3);
}

export function BatchAddScore(arg1, arg2, arg3) {
  return window['go']['app']['App']['BatchAddScore'](arg1, arg2, arg3);
}

export function ClearRollCallLogs(arg1) {
  return window['go']['app']['App']['ClearRollCallLogs'](arg1);
}

export function ConfirmImport(arg1, arg2) {
  return window['go']['app']['App']['ConfirmImport'](arg1, arg2);
}

export function CreateClass(arg1) {
  return window['go']['app']['App']['CreateClass'](arg1);
}

export function CreateStudent(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateStudent'](arg1, arg2, arg3, arg4);
}

export function DeleteClass(arg1) {
  return window['go']['app']['App']['DeleteClass'](arg1);
}

export function DeleteStudent(arg1) {
  return window['go']['app']['App']['DeleteStudent'](arg1);
}

export function DoRollCall(arg1, arg2) {
  return window['go']['app']['App']['DoRollCall'](arg1, arg2);
}

export function ExportStudents(arg1) {
  return window['go']['app']['App']['ExportStudents'](arg1);
}

export function GetClassStudentCount(arg1) {
  return window['go']['app']['App']['GetClassStudentCount'](arg1);
}

export function GetClasses() {
  return window['go']['app']['App']['GetClasses']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetDefaultClass() {
  return window['go']['app']['App']['GetDefaultClass']();
}

export function GetRollCallLogs(arg1, arg2) {
  return window['go']['app']['App']['GetRollCallLogs'](arg1, arg2);
}

export function GetScoreLogs(arg1) {
  return window['go']['app']['App']['GetScoreLogs'](arg1);
}

export function GetScoreLogsByClass(arg1) {
  return window['go']['app']['App']['GetScoreLogsByClass'](arg1);
}

export function GetStudents(arg1) {
  return window['go']['app']['App']['GetStudents'](arg1);
}

export function GetWeightInfo(arg1) {
  return window['go']['app']['App']['GetWeightInfo'](arg1);
}

export function HasAdminPassword() {
  return window['go']['app']['App']['HasAdminPassword']();
}

export function PreviewImport() {
  return window['go']['app']['App']['PreviewImport']();
}

export function PreviewImportText(arg1) {
  return window['go']['app']['App']['PreviewImportText'](arg1);
}

export function ReportRollCallResult(arg1, arg2) {
  return window['go']['app']['App']['ReportRollCallResult'](arg1, arg2);
}

export function SearchStudents(arg1, arg2) {
  return window['go']['app']['App']['SearchStudents'](arg1, arg2);
}

export function SetAdminPassword(arg1, arg2) {
  return window['go']['app']['App']['SetAdminPassword'](arg1, arg2);
}

export function SetDefaultClass(arg1) {
  return window['go']['app']['App']['SetDefaultClass'](arg1);
}

export function UpdateClass(arg1, arg2) {
  return window['go']['app']['App']['UpdateClass'](arg1, arg2);
}

export function UpdateConfig(arg1) {
  return window['go']['app']['App']['UpdateConfig'](arg1);
}

export function UpdateStudent(arg1) {
  return window['go']['app']['App']['UpdateStudent'](arg1);
}

export function VerifyAdminPassword(arg1) {
  return window['go']['app']['App']['VerifyAdminPassword'](arg1);
}
