// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {config} from '../models';
import {service} from '../models';

export function AddScore(arg1:number,arg2:number,arg3:string):Promise<void>;

export function BatchAddScore(arg1:Array<number>,arg2:number,arg3:string):Promise<void>;

export function ClearRollCallLogs(arg1:number):Promise<void>;

export function ConfirmImport(arg1:number,arg2:Array<model.Student>):Promise<number>;

export function CreateClass(arg1:string):Promise<model.Class>;

export function CreateStudent(arg1:number,arg2:string,arg3:string,arg4:string):Promise<model.Student>;

export function DeleteClass(arg1:number):Promise<void>;

export function DeleteStudent(arg1:number):Promise<void>;

export function DoRollCall(arg1:number,arg2:number):Promise<Array<model.Student>>;

export function ExportStudents(arg1:number):Promise<void>;

export function GetClassStudentCount(arg1:number):Promise<number>;

export function GetClasses():Promise<Array<model.Class>>;

export function GetConfig():Promise<config.Config>;

export function GetDefaultClass():Promise<model.Class>;

export function GetRollCallLogs(arg1:number,arg2:number):Promise<Array<model.RollCallLog>>;

export function GetScoreLogs(arg1:number):Promise<Array<model.ScoreLog>>;

export function GetScoreLogsByClass(arg1:number):Promise<Array<model.ScoreLog>>;

export function GetStudents(arg1:number):Promise<Array<model.Student>>;

export function GetWeightInfo(arg1:number):Promise<Array<service.StudentWeightInfo>>;

export function HasAdminPassword():Promise<boolean>;

export function PreviewImport():Promise<Array<model.Student>>;

export function PreviewImportText(arg1:string):Promise<Array<model.Student>>;

export function ReportRollCallResult(arg1:number,arg2:Array<number>):Promise<Array<model.Student>>;

export function SearchStudents(arg1:number,arg2:string):Promise<Array<model.Student>>;

export function SetAdminPassword(arg1:string,arg2:string):Promise<void>;

export function SetDefaultClass(arg1:number):Promise<void>;

export function UpdateClass(arg1:number,arg2:string):Promise<void>;

export function UpdateConfig(arg1:config.Config):Promise<void>;

export function UpdateStudent(arg1:model.Student):Promise<void>;

export function VerifyAdminPassword(arg1:string):Promise<boolean>;
